# Generated by Django 3.2.25 on 2024-04-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
